<<<<<<< HEAD:.github/worflows/cicd.yaml
# CICD using GitHub actions

name: CI/CD

# Exclude the workflow to run on changes to the helm chart
on:
=======
#naming workflow
name: Continous Integration
# providing build-triggers(like jenkins)
on: 
>>>>>>> 3e5c29cedb1021552586311f6829b94bab040969:.github/worflows/ci.yaml
  push:
    branches:
    - main
    paths-ignore:
<<<<<<< HEAD:.github/worflows/cicd.yaml
      - 'helm/**'
      - 'k8s/**'
      - 'README.md'
=======
    - 'README.md'
    - 'helm/**'
  workflow_dispatch:  # This will allow you to manually run the workflow.


# build stage: need to provide a VM or container with an ubuntu image where github actions will run this particular 
#stage.here github actions is using its own runner . we can use our own runner or ask github to use itss runner.
#runner is using ubuntu-latest image.
# every stage should have a image cz github actions need to execute this on runner.
# so it needs to knw on which runner it needs to run. 
>>>>>>> 3e5c29cedb1021552586311f6829b94bab040969:.github/worflows/ci.yaml

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go 1.22
      uses: actions/setup-go@v2
      with:
        go-version: 1.23

    - name: Build
      run: go build -o go-web-app

    - name: Test
      run: go test ./...
  
  code-quality:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.56.2
  
  push:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

<<<<<<< HEAD:.github/worflows/cicd.yaml
    - name: Set up Docker Buildx
=======
    - name: Setup Docker Buildx
>>>>>>> 3e5c29cedb1021552586311f6829b94bab040969:.github/worflows/ci.yaml
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push action
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/go-web-app:${{github.run_id}}

  update-newtag-in-helm-chart:
    runs-on: ubuntu-latest

    needs: push

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.TOKEN }}

    - name: Update tag in Helm chart
      run: |
        sed -i 's/tag: .*/tag: "${{github.run_id}}"/' helm/go-web-app-chart/values.yaml

    - name: Commit and push changes
<<<<<<< HEAD:.github/worflows/cicd.yaml
      run: |
        git config --global user.email "ssd125agarwal@gmail.com"
        git config --global user.name "SRUSHTI-AGARWAL"
        git add helm/go-web-app-chart/values.yaml
        git commit -m "Update tag in Helm chart"
        git push

=======
      run: |    
        git  config --global user.email "ssd125agarwal@gmail.com"
        git config --global user.name "SRUSHTI-AGARWAL"
        git add helm/helm-go-web-app-chart/values.yaml
        git commit -m "Update tag in helm chart"
        git push 
>>>>>>> 3e5c29cedb1021552586311f6829b94bab040969:.github/worflows/ci.yaml
